name: xeus-kernel
channels:
  - https://repo.prefix.dev/emscripten-forge-4x
  - https://repo.prefix.dev/conda-forge
dependencies:
  - xeus-python
  - ipycanvas
  - cddlib
  - lrcalc-python
  - networkx
  - numpy
  - python-igraph
  - scipy
  - passagemath-categories
  - passagemath-cmr
  - passagemath-combinat
  - passagemath-environment
  - passagemath-glpk
  - passagemath-graphs
  - passagemath-highs
  - passagemath-modules
  - passagemath-objects
  - passagemath-ppl
  - passagemath-plot
  - passagemath-repl
  - passagemath-tdlib
