name: xeus-kernel
channels:
  - https://repo.prefix.dev/emscripten-forge
  - https://repo.prefix.dev/conda-forge
dependencies:
  - xeus-python
  - ipycanvas
  - passagemath-cmr
  - passagemath-combinat
  - passagemath-repl
